# Colors (onedark-cool)

# Default colors
[colors.primary]
background = '#242b38'
foreground = '#a5b0c5'

# Normal colors
[colors.normal]
black   = '#546178'
red     = '#ef5f6b'
green   = '#97ca72'
yellow  = '#ebc275'
blue    = '#5ab0f6'
magenta = '#ca72e4'
cyan    = '#4dbdcb'
white   = '#a5b0c5'

# Bright colors
[colors.bright]
black   = '#151820'
red     = '#ef5f6b'
green   = '#97ca72'
yellow  = '#ebc275'
blue    = '#5ab0f6'
magenta = '#ca72e4'
cyan    = '#4dbdcb'
white   = '#a5b0c5'
