# Colors (onedark-deep)

# Default colors
[colors.primary]
background = '#1a212e'
foreground = '#93a4c3'

# Normal colors
[colors.normal]
black   = '#455574'
red     = '#f65866'
green   = '#8bcd5b'
yellow  = '#efbd5d'
blue    = '#41a7fc'
magenta = '#c75ae8'
cyan    = '#34bfd0'
white   = '#93a4c3'

# Bright colors
[colors.bright]
black   = '#0c0e15'
red     = '#f65866'
green   = '#8bcd5b'
yellow  = '#efbd5d'
blue    = '#41a7fc'
magenta = '#c75ae8'
cyan    = '#34bfd0'
white   = '#93a4c3'
