vim.o.background = 'dark'
vim.cmd.hi('clear')
vim.g.colors_name = 'onedark'

vim.opt.termguicolors = true

local theme = {
  hl = {
    ["@annotation"] = { fg = "#d75271" },
    ["@attribute"] = { fg = "#169AC9" },
    ["@character"] = { fg = "#db627e" },
    ["@comment"] = { fg = "#404040" },
    ["@comment.danger"] = { bg = "#db627e", fg = "#181818" },
    ["@comment.note"] = { bg = "#25B0BC", fg = "#0e0e0e" },
    ["@comment.todo"] = { bg = "#FFFFFF", fg = "#363636" },
    ["@comment.warning"] = { bg = "#eaa273", fg = "#181818" },
    ["@constant"] = { fg = "#eaa273" },
    ["@constant.builtin"] = { fg = "#eaa273" },
    ["@constant.macro"] = { fg = "#db627e" },
    ["@constructor"] = { fg = "#F09483" },
    ["@definition"] = { sp = "#3f4248", underline = true },
    ["@diff.delta"] = { fg = "#525252" },
    ["@diff.minus"] = { fg = "#db627e" },
    ["@diff.plus"] = { fg = "#AAD84C" },
    ["@error"] = { fg = "#db627e" },
    ["@function"] = { fg = "#32d5e3" },
    ["@function.builtin"] = { fg = "#32d5e3" },
    ["@function.call"] = { fg = "#32d5e3" },
    ["@function.macro"] = { fg = "#db627e" },
    ["@function.method"] = { fg = "#32d5e3" },
    ["@function.method.call"] = { fg = "#32d5e3" },
    ["@keyword"] = { fg = "#6BE4E6" },
    ["@keyword.conditional"] = { fg = "#6BE4E6" },
    ["@keyword.conditional.ternary"] = { fg = "#6BE4E6" },
    ["@keyword.directive"] = { fg = "#169AC9" },
    ["@keyword.directive.define"] = { fg = "#6BE4E6" },
    ["@keyword.exception"] = { fg = "#db627e" },
    ["@keyword.function"] = { fg = "#6BE4E6" },
    ["@keyword.import"] = { link = "Include" },
    ["@keyword.operator"] = { fg = "#6BE4E6" },
    ["@keyword.repeat"] = { fg = "#169AC9" },
    ["@keyword.return"] = { fg = "#6BE4E6" },
    ["@keyword.storage"] = { fg = "#169AC9" },
    ["@markup.heading"] = { fg = "#32d5e3" },
    ["@markup.italic"] = { italic = true },
    ["@markup.link"] = { fg = "#db627e" },
    ["@markup.link.label"] = { fg = "#F09483" },
    ["@markup.link.url"] = { fg = "#eaa273", underline = true },
    ["@markup.list"] = { fg = "#db627e" },
    ["@markup.quote"] = { bg = "#181818" },
    ["@markup.raw"] = { fg = "#eaa273" },
    ["@markup.strikethrough"] = { strikethrough = true },
    ["@markup.strong"] = { bold = true },
    ["@markup.underline"] = { underline = true },
    ["@module"] = { fg = "#db627e" },
    ["@number"] = { fg = "#eaa273" },
    ["@number.float"] = { fg = "#eaa273" },
    ["@operator"] = { fg = "#c9c7be" },
    ["@property"] = { fg = "#6BE4E6" },
    ["@punctuation.bracket"] = { fg = "#fdb830" },
    ["@punctuation.delimiter"] = { fg = "#fdb830" },
    ["@reference"] = { fg = "#c9c7be" },
    ["@scope"] = { bold = true },
    ["@string"] = { fg = "#E3A587" },
    ["@string.escape"] = { fg = "#F09483" },
    ["@string.regex"] = { fg = "#F09483" },
    ["@symbol"] = { fg = "#E3A587" },
    ["@tag"] = { fg = "#169AC9" },
    ["@tag.attribute"] = { fg = "#db627e" },
    ["@tag.delimiter"] = { fg = "#c9c7be" },
    ["@text"] = { fg = "#c9c7be" },
    ["@text.emphasis"] = { fg = "#eaa273" },
    ["@text.strike"] = { fg = "#d75271", strikethrough = true },
    ["@type.builtin"] = { fg = "#169AC9" },
    ["@variable"] = { fg = "#c9c7be" },
    ["@variable.builtin"] = { fg = "#eaa273" },
    ["@variable.member"] = { fg = "#db627e" },
    ["@variable.member.key"] = { fg = "#db627e" },
    ["@variable.parameter"] = { fg = "#db627e" },
    Added = { fg = "#AAD84C" },
    BlinkCmpDoc = { bg = "#0e0e0e" },
    BlinkCmpDocBorder = { fg = "#404040" },
    BlinkCmpDocCursorLine = { bg = "#1c1c1c" },
    BlinkCmpDocSeparator = { fg = "#363636" },
    BlinkCmpGhostText = { fg = "#404040" },
    BlinkCmpKindClass = { fg = "#749689" },
    BlinkCmpKindCodeium = { fg = "#b9e75b" },
    BlinkCmpKindColor = { fg = "#FFFFFF" },
    BlinkCmpKindConstant = { fg = "#eaa273" },
    BlinkCmpKindConstructor = { fg = "#25B0BC" },
    BlinkCmpKindCopilot = { fg = "#AAD84C" },
    BlinkCmpKindEnum = { fg = "#25B0BC" },
    BlinkCmpKindEnumMember = { fg = "#da70d6" },
    BlinkCmpKindEvent = { fg = "#fdb830" },
    BlinkCmpKindField = { fg = "#db627e" },
    BlinkCmpKindFile = { fg = "#D9D7CE" },
    BlinkCmpKindFolder = { fg = "#D9D7CE" },
    BlinkCmpKindFunction = { fg = "#32d5e3" },
    BlinkCmpKindIdentifier = { fg = "#db627e" },
    BlinkCmpKindInterface = { fg = "#AAD84C" },
    BlinkCmpKindKeyword = { fg = "#D9D7CE" },
    BlinkCmpKindMethod = { fg = "#32d5e3" },
    BlinkCmpKindModule = { fg = "#169AC9" },
    BlinkCmpKindOperator = { fg = "#c9c7be" },
    BlinkCmpKindProperty = { fg = "#db627e" },
    BlinkCmpKindReference = { fg = "#c9c7be" },
    BlinkCmpKindSnippet = { fg = "#db627e" },
    BlinkCmpKindStruct = { fg = "#6BE4E6" },
    BlinkCmpKindStructure = { fg = "#6BE4E6" },
    BlinkCmpKindSuperMaven = { fg = "#fdb830" },
    BlinkCmpKindTabNine = { fg = "#a72e5b" },
    BlinkCmpKindText = { fg = "#E3A587" },
    BlinkCmpKindType = { fg = "#169AC9" },
    BlinkCmpKindTypeParameter = { fg = "#db627e" },
    BlinkCmpKindUnit = { fg = "#6BE4E6" },
    BlinkCmpKindValue = { fg = "#6BE4E6" },
    BlinkCmpKindVariable = { fg = "#6BE4E6" },
    BlinkCmpLabel = { fg = "#FFFFFF" },
    BlinkCmpLabelDeprecated = { fg = "#db627e", strikethrough = true },
    BlinkCmpLabelDescription = { fg = "#525252" },
    BlinkCmpLabelDetail = { fg = "#525252" },
    BlinkCmpLabelMatch = { bold = true, fg = "#25B0BC" },
    BlinkCmpMenu = { bg = "#0e0e0e" },
    BlinkCmpMenuBorder = { fg = "#404040" },
    BlinkCmpMenuSelection = { bold = true, link = "PmenuSel" },
    BlinkCmpScrollBarGutter = { bg = "#181818" },
    BlinkCmpScrollBarThumb = { bg = "#363636" },
    BlinkCmpSignatureHelp = { bg = "#0e0e0e" },
    BlinkCmpSignatureHelpActiveParameter = { bold = true, fg = "#25B0BC" },
    BlinkCmpSignatureHelpBorder = { fg = "#404040" },
    BlinkCmpSource = { fg = "#404040" },
    Boolean = { fg = "#eaa273" },
    Changed = { fg = "#fdb830" },
    Character = { fg = "#db627e" },
    ColorColumn = { bg = "#181818" },
    Comment = { fg = "#525252" },
    Conceal = { bg = "NONE" },
    Conditional = { fg = "#6BE4E6" },
    Constant = { fg = "#eaa273" },
    Cursor = { bg = "#c9c7be", fg = "#0e0e0e" },
    CursorColumn = { bg = "#181818" },
    CursorLine = { bg = "#181818" },
    CursorLineNr = { fg = "#FFFFFF" },
    Debug = { fg = "#db627e" },
    Define = { fg = "#6BE4E6", sp = "none" },
    Delimiter = { fg = "#d75271" },
    DevIconDart = { fg = "#6BE4E6" },
    DevIconDefault = { fg = "#db627e" },
    DevIconDockerfile = { fg = "#6BE4E6" },
    DevIconJSX = { fg = "#25B0BC" },
    DevIconJava = { fg = "#FFA500" },
    DevIconMd = { fg = "#25B0BC" },
    DevIconSvelte = { fg = "#db627e" },
    DevIconTSX = { fg = "#25B0BC" },
    DevIconZig = { fg = "#FFA500" },
    DevIconc = { fg = "#25B0BC" },
    DevIconcss = { fg = "#25B0BC" },
    DevIcondeb = { fg = "#6BE4E6" },
    DevIconhtml = { fg = "#a72e5b" },
    DevIconjpeg = { fg = "#c65cc2" },
    DevIconjpg = { fg = "#c65cc2" },
    DevIconjs = { fg = "#ffc038" },
    DevIconkt = { fg = "#FFA500" },
    DevIconlock = { fg = "#db627e" },
    DevIconlua = { fg = "#25B0BC" },
    DevIconmp3 = { fg = "#FFFFFF" },
    DevIconmp4 = { fg = "#FFFFFF" },
    DevIconout = { fg = "#FFFFFF" },
    DevIconpng = { fg = "#c65cc2" },
    DevIconpy = { fg = "#6BE4E6" },
    DevIconrb = { fg = "#ff75a0" },
    DevIconrpm = { fg = "#FFA500" },
    DevIcontoml = { fg = "#25B0BC" },
    DevIconts = { fg = "#749689" },
    DevIconttf = { fg = "#FFFFFF" },
    DevIconvue = { fg = "#b9e75b" },
    DevIconwoff = { fg = "#FFFFFF" },
    DevIconwoff2 = { fg = "#FFFFFF" },
    DevIconxz = { fg = "#ffc038" },
    DevIconzip = { fg = "#ffc038" },
    DiagnosticError = { fg = "#db627e" },
    DiagnosticHint = { fg = "#da70d6" },
    DiagnosticInfo = { fg = "#AAD84C" },
    DiagnosticWarn = { fg = "#fdb830" },
    DiffAdd = { bg = "#1d2214", fg = "#AAD84C" },
    DiffAdded = { bg = "#1d2214", fg = "#AAD84C" },
    DiffChange = { bg = "#141414", fg = "#525252" },
    DiffChangeDelete = { bg = "#221619", fg = "#db627e" },
    DiffDelete = { bg = "#221619", fg = "#db627e" },
    DiffModified = { bg = "#261d0c", fg = "#FFA500" },
    DiffRemoved = { bg = "#221619", fg = "#db627e" },
    DiffText = { bg = "#181818", fg = "#FFFFFF" },
    Directory = { fg = "#32d5e3" },
    Error = { bg = "#db627e", fg = "#0e0e0e" },
    ErrorMsg = { bg = "#0e0e0e", fg = "#db627e" },
    Exception = { fg = "#db627e" },
    Float = { fg = "#eaa273" },
    FloatBorder = { fg = "#25B0BC" },
    FloatTitle = { bg = "#363636", fg = "#FFFFFF" },
    FoldColumn = { bg = "none" },
    Folded = { bg = "#181818", fg = "#525252" },
    Function = { fg = "#32d5e3" },
    Identifier = { fg = "#db627e", sp = "none" },
    IncSearch = { bg = "#eaa273", fg = "#181818" },
    Include = { bold = true, fg = "#6BE4E6" },
    Keyword = { fg = "#6BE4E6" },
    Label = { fg = "#169AC9" },
    LazyButton = { bg = "#1c1c1c", fg = "#6b6b6b" },
    LazyCommit = { fg = "#AAD84C" },
    LazyCommitIssue = { fg = "#ff75a0" },
    LazyDir = { fg = "#c9c7be" },
    LazyH1 = { bg = "#AAD84C", fg = "#0e0e0e" },
    LazyH2 = { bold = true, fg = "#db627e", underline = true },
    LazyNoCond = { fg = "#db627e" },
    LazyOperator = { fg = "#FFFFFF" },
    LazyProgressDone = { fg = "#AAD84C" },
    LazyReasonCmd = { fg = "#ffc038" },
    LazyReasonEvent = { fg = "#fdb830" },
    LazyReasonFt = { fg = "#da70d6" },
    LazyReasonImport = { fg = "#FFFFFF" },
    LazyReasonKeys = { fg = "#749689" },
    LazyReasonPlugin = { fg = "#db627e" },
    LazyReasonRuntime = { fg = "#18a3af" },
    LazyReasonSource = { fg = "#6BE4E6" },
    LazyReasonStart = { fg = "#FFFFFF" },
    LazySpecial = { fg = "#25B0BC" },
    LazyTaskOutput = { fg = "#FFFFFF" },
    LazyUrl = { fg = "#c9c7be" },
    LazyValue = { fg = "#749689" },
    LineNr = { fg = "#363636" },
    LspInlayHint = { bg = "#181818", fg = "#525252" },
    LspReferenceRead = { bg = "#292929" },
    LspReferenceText = { bg = "#292929" },
    LspReferenceWrite = { bg = "#292929" },
    LspSignatureActiveParameter = { bg = "#AAD84C", fg = "#0e0e0e" },
    Macro = { fg = "#db627e" },
    MasonHeader = { bg = "#db627e", fg = "#0e0e0e" },
    MasonHeaderSecondary = { link = "MasonHighlightBlock" },
    MasonHighlight = { fg = "#25B0BC" },
    MasonHighlightBlock = { bg = "#AAD84C", fg = "#0e0e0e" },
    MasonHighlightBlockBold = { link = "MasonHighlightBlock" },
    MasonMuted = { fg = "#525252" },
    MasonMutedBlock = { bg = "#1c1c1c", fg = "#525252" },
    MatchParen = { link = "MatchWord" },
    MatchWord = { bg = "#363636", fg = "#FFFFFF" },
    ModeMsg = { fg = "#E3A587" },
    MoreMsg = { fg = "#E3A587" },
    NonText = { fg = "#363636" },
    Normal = { bg = "#0e0e0e", fg = "#c9c7be" },
    NormalFloat = { bg = "#080808" },
    Number = { fg = "#eaa273" },
    NvDashAscii = { fg = "#25B0BC" },
    NvDashButtons = { fg = "#525252" },
    NvDashFooter = { fg = "#db627e" },
    NvimInternalError = { fg = "#db627e" },
    Operator = { fg = "#c9c7be", sp = "none" },
    Pmenu = { bg = "#1c1c1c" },
    PmenuSbar = { bg = "#1c1c1c" },
    PmenuSel = { bg = "#15bf84", fg = "#0e0e0e" },
    PmenuThumb = { bg = "#363636" },
    PreProc = { fg = "#169AC9" },
    Question = { fg = "#32d5e3" },
    QuickFixLine = { bg = "#181818" },
    Removed = { fg = "#db627e" },
    Repeat = { fg = "#169AC9" },
    Search = { bg = "#169AC9", fg = "#181818" },
    SignColumn = { fg = "#363636" },
    Special = { fg = "#F09483" },
    SpecialChar = { fg = "#d75271" },
    SpecialKey = { fg = "#363636" },
    Statement = { fg = "#db627e" },
    StatusLine = { bg = "#181818" },
    StorageClass = { fg = "#169AC9" },
    String = { fg = "#E3A587" },
    Structure = { fg = "#6BE4E6" },
    Substitute = { bg = "#169AC9", fg = "#181818" },
    Tag = { fg = "#169AC9" },
    Title = { fg = "#32d5e3" },
    Todo = { bg = "#181818", fg = "#169AC9" },
    TooLong = { fg = "#db627e" },
    Type = { fg = "#169AC9", sp = "none" },
    Typedef = { fg = "#169AC9" },
    Variable = { fg = "#c9c7be" },
    Visual = { bg = "#292929" },
    VisualNOS = { fg = "#db627e" },
    WarningMsg = { fg = "#db627e" },
    WhichKey = { fg = "#25B0BC" },
    WhichKeyDesc = { fg = "#db627e" },
    WhichKeyGroup = { fg = "#AAD84C" },
    WhichKeySeparator = { fg = "#525252" },
    WhichKeyValue = { fg = "#AAD84C" },
    WildMenu = { bg = "#169AC9", fg = "#db627e" },
    WinBar = { bg = "NONE" },
    WinBarNC = { bg = "NONE" },
    WinSeparator = { fg = "#1d1d1d" },
    diffNewFile = { fg = "#25B0BC" },
    diffOldFile = { fg = "#a72e5b" },
    gitcommitBranch = { bold = true, fg = "#eaa273" },
    gitcommitComment = { fg = "#363636" },
    gitcommitDiscarded = { fg = "#363636" },
    gitcommitDiscardedFile = { bold = true, fg = "#db627e" },
    gitcommitDiscardedType = { fg = "#32d5e3" },
    gitcommitHeader = { fg = "#6BE4E6" },
    gitcommitOverflow = { fg = "#db627e" },
    gitcommitSelected = { fg = "#363636" },
    gitcommitSelectedFile = { bold = true, fg = "#E3A587" },
    gitcommitSelectedType = { fg = "#32d5e3" },
    gitcommitSummary = { fg = "#E3A587" },
    gitcommitUnmergedFile = { bold = true, fg = "#db627e" },
    gitcommitUnmergedType = { fg = "#32d5e3" },
    gitcommitUntracked = { fg = "#363636" },
    gitcommitUntrackedFile = { fg = "#169AC9" },
    healthSuccess = { bg = "#AAD84C", fg = "#0e0e0e" }
  },
  term = {
    { bright = "#363636", dark = "#181818" },
    { bright = "#db627e", dark = "#db627e" },
    { bright = "#E3A587", dark = "#E3A587" },
    { bright = "#169AC9", dark = "#169AC9" },
    { bright = "#32d5e3", dark = "#32d5e3" },
    { bright = "#6BE4E6", dark = "#6BE4E6" },
    { bright = "#F09483", dark = "#F09483" },
    { bright = "#D9D7CE", dark = "#c9c7be" }
  }
}


require('highlights').apply_highlights(theme.hl)
require('highlights').apply_term(theme.term)
