-- credit: https://github.com/notken12/base46-colors
vim.o.background = 'dark'
vim.cmd.hi('clear')

vim.opt.termguicolors = true
vim.g.colors_name = 'everblush'

local c = {
  white = "#dadada",
  darker_black = "#10171a",
  black = "#141b1e",
  black2 = "#1a2124",
  one_bg = "#1e2528",
  one_bg2 = "#272e31",
  one_bg3 = "#2f3639",
  grey = "#3c4346",
  grey_fg = "#464d50",
  grey_fg2 = "#565b60",
  light_grey = "#50575a",
  red = "#e57474",
  baby_pink = "#f48383",
  pink = "#ee9cdd",
  line = "#22292b",
  green = "#8ccf7e",
  vibrant_green = "#86d988",
  nord_blue = "#5aa3db",
  blue = "#67b0e8",
  yellow = "#e5c76b",
  sun = "#edcf73",
  purple = "#c47fd5",
  dark_purple = "#b570c6",
  teal = "#9bdead",
  orange = "#fcb163",
  cyan = "#6cbfbf",
  statusline_bg = "#1b2528",
  lightbg = "#262d30",
  lightbg2 = "#1f2629",
  pmenu_bg = "#8ccf7e",
  folder_bg = "#71baf2",
  base00 = "#141b1e",
  base01 = "#1e2528",
  base02 = "#282f32",
  base03 = "#2d3437",
  base04 = "#3c4346",
  base05 = "#dadada",
  base06 = "#e4e4e4",
  base07 = "#dadada",
  base08 = "#e57474",
  base09 = "#fcb163",
  base0A = "#e5c76b",
  base0B = "#8ccf7e",
  base0C = "#6cbfbf",
  base0D = "#67b0e8",
  base0E = "#c47fd5",
  base0F = "#ef7d7d",
}

local ansi_term = {
  { dark = c.base01, bright = c.base03, },     -- black
  { dark = c.base08, bright = c.base08, },    -- red
  { dark = c.base0B, bright = c.base0B, },   -- green
  { dark = c.base0A, bright = c.base0A, }, -- yellow
  { dark = c.base0D, bright = c.base0D, },   -- blue
  { dark = c.base0E, bright = c.base0E, }, -- magenta
  { dark = c.base0C, bright = c.base0C, },  -- cyan
  { dark = c.base05, bright = c.base06, },     -- white
}

for i, color in ipairs(ansi_term) do
  vim.g['terminal_color_' .. (i - 1)] = color.dark
  vim.g['terminal_color_' .. (i - 1 + 8)] = color.bright
end

local theme = {
  Normal = { fg = c.base05, bg = c.base00 },
  SignColumn = { fg = c.base03, bg = 'NONE', sp = 'NONE', },
  MsgArea = { fg = c.base05, bg = c.base00 },
  ModeMsg = { fg = c.base0B, bg = 'NONE' },
  MsgSeparator = { fg = c.base05, bg = c.base00 },
  SpellBad = { fg = 'NONE', bg = 'NONE', sp = c.base08, undercurl = true, },
  SpellCap = { fg = 'NONE', bg = 'NONE', sp = c.base0D, undercurl = true, },
  SpellLocal = { fg = 'NONE', bg = 'NONE', sp = c.base0C, undercurl = true, },
  SpellRare = { fg = 'NONE', bg = 'NONE', sp = c.base0D, undercurl = true, },
  NormalNC = { fg = c.base05, bg = c.base00 },
  Pmenu = { fg = 'NONE', bg = c.one_bg },
  PmenuSel = { fg = c.black, bg = c.pmenu_bg },
  WildMenu = { fg = c.base08, bg = c.base0A },
  CursorLineNr = { fg = c.white, bg = 'NONE' },
  Comment = { fg = c.grey_fg, bg = 'NONE' },
  Folded = { fg = c.base03, bg = c.base01 },
  FoldColumn = { fg = c.base0C, bg = c.base01 },
  LineNr = { fg = c.grey_fg2, bg = 'NONE' },
  FloatBorder = { fg = c.line, bg = c.darker_black },
  Float = { fg = c.base09, bg = 'NONE' },
  NormalFloat = { fg = 'NONE', bg = c.darker_black },
  VertSplit = { fg = c.line, bg = 'NONE' },
  WinSeparator = { fg = c.line, bg = 'NONE' },
  CursorLine = { fg = 'NONE', bg = c.black2 },
  CursorColumn = { fg = 'NONE', bg = c.black2 },
  ColorColumn = { fg = 'NONE', bg = c.black2 },
  Visual = { fg = 'NONE', bg = c.base02 },
  VisualNOS = { fg = c.base08, bg = 'NONE' },
  WarningMsg = { fg = c.base08, bg = 'NONE' },
  DiffAdd = { fg = c.vibrant_green, bg = 'NONE' },
  DiffChange = { fg = c.blue, bg = 'NONE' },
  DiffDelete = { fg = c.red, bg = 'NONE' },
  Added = { fg = c.vibrant_green, bg = 'NONE' },
  Changed = { fg = c.blue, bg = 'NONE' },
  Removed = { fg = c.red, bg = 'NONE' },
  QuickFixLine = { fg = 'NONE', bg = c.base01, sp = 'NONE', },
  PmenuSbar = { fg = 'NONE', bg = c.one_bg },
  PmenuThumb = { fg = 'NONE', bg = c.grey },
  MatchWord = { fg = c.white, bg = c.grey },
  MatchParen = { link = 'MatchWord' },
  Cursor = { fg = c.base00, bg = c.base05 },
  Conceal = { fg = 'NONE', bg = 'NONE' },
  Directory = { fg = c.base0D, bg = 'NONE' },
  SpecialKey = { fg = c.base03, bg = 'NONE' },
  Title = { fg = c.base0D, bg = 'NONE', sp = 'NONE', },
  ErrorMsg = { fg = c.base08, bg = c.base00 },
  Search = { fg = c.base01, bg = c.base0A },
  IncSearch = { fg = c.base01, bg = c.base09 },
  Substitute = { fg = c.base01, bg = c.base0A, sp = 'NONE', },
  MoreMsg = { fg = c.base0B, bg = 'NONE' },
  Question = { fg = c.base0D, bg = 'NONE' },
  NonText = { fg = c.base03, bg = 'NONE' },
  Variable = { fg = c.base05, bg = 'NONE' },
  String = { fg = c.base0B, bg = 'NONE' },
  Character = { fg = c.base08, bg = 'NONE' },
  Constant = { fg = c.base08, bg = 'NONE' },
  Number = { fg = c.base09, bg = 'NONE' },
  Boolean = { fg = c.base09, bg = 'NONE' },
  Identifier = { fg = c.base08, bg = 'NONE', sp = 'NONE', },
  Function = { fg = c.base0D, bg = 'NONE' },
  Operator = { fg = c.base05, bg = 'NONE', sp = 'NONE', },
  Type = { fg = c.base0A, bg = 'NONE', sp = 'NONE', },
  StorageClass = { fg = c.base0A, bg = 'NONE' },
  Structure = { fg = c.base0E, bg = 'NONE' },
  Typedef = { fg = c.base0A, bg = 'NONE' },
  Keyword = { fg = c.base0E, bg = 'NONE' },
  Statement = { fg = c.base08, bg = 'NONE' },
  Conditional = { fg = c.base0E, bg = 'NONE' },
  Repeat = { fg = c.base0A, bg = 'NONE' },
  Label = { fg = c.base0A, bg = 'NONE' },
  Exception = { fg = c.base08, bg = 'NONE' },
  Include = { fg = c.base0D, bg = 'NONE' },
  PreProc = { fg = c.base0A, bg = 'NONE' },
  Define = { fg = c.base0E, bg = 'NONE', sp = 'NONE', },
  Macro = { fg = c.base08, bg = 'NONE' },
  Special = { fg = c.base0C, bg = 'NONE' },
  SpecialChar = { fg = c.base0F, bg = 'NONE' },
  Tag = { fg = c.base0A, bg = 'NONE' },
  Debug = { fg = c.base08, bg = 'NONE' },
  Underlined = { fg = c.base0B, bg = 'NONE' },
  Bold = { fg = 'NONE', bg = 'NONE', bold = true, },
  Italic = { fg = 'NONE', bg = 'NONE', italic = true, },
  Ignore = { fg = c.cyan, bg = c.base00, bold = true, },
  Todo = { fg = c.base0A, bg = c.base01 },
  Error = { fg = c.base00, bg = c.base08 },
  TabLine = { fg = c.grey_fg2, bg = c.line },
  TabLineSel = { fg = c.white, bg = 'NONE' },
  TabLineFill = { fg = c.line, bg = c.line },

  -- Treesitter
  ["@annotation"] = { fg = c.base0F, bg = 'NONE' },
  ["@attribute"] = { fg = c.base0A, bg = 'NONE' },
  ["@constructor"] = { fg = c.base0C, bg = 'NONE' },
  ["@type.builtin"] = { fg = c.base0A, bg = 'NONE' },
  ["@conditional"] = { link = 'Conditional' },
  ["@exception"] = { fg = c.base08, bg = 'NONE' },
  ["@include"] = { link = 'Include' },
  ["@keyword.return"] = { fg = c.base0E, bg = 'NONE' },
  ["@keyword"] = { fg = c.base0E, bg = 'NONE' },
  ["@keyword.function"] = { fg = c.base0E, bg = 'NONE' },
  ["@namespace"] = { fg = c.base08, bg = 'NONE' },
  ["@constant.builtin"] = { fg = c.base09, bg = 'NONE' },
  ["@float"] = { fg = c.base09, bg = 'NONE' },
  ["@character"] = { fg = c.base08, bg = 'NONE' },
  ["@error"] = { fg = c.base08, bg = 'NONE' },
  ["@function"] = { fg = c.base0D, bg = 'NONE' },
  ["@function.builtin"] = { fg = c.base0D, bg = 'NONE' },
  ["@method"] = { fg = c.base0D, bg = 'NONE' },
  ["@constant.macro"] = { fg = c.base08, bg = 'NONE' },
  ["@function.macro"] = { fg = c.base08, bg = 'NONE' },
  ["@variable"] = { fg = c.base05, bg = 'NONE' },
  ["@variable.builtin"] = { fg = c.base09, bg = 'NONE' },
  ["@property"] = { fg = c.base08, bg = 'NONE' },
  ["@field"] = { fg = c.base0D, bg = 'NONE' },
  ["@parameter"] = { fg = c.base08, bg = 'NONE' },
  ["@parameter.reference"] = { fg = c.base05, bg = 'NONE' },
  ["@symbol"] = { fg = c.base0B, bg = 'NONE' },
  ["@text"] = { fg = c.base05, bg = 'NONE' },
  ["@punctuation.delimiter"] = { fg = c.base0F, bg = 'NONE' },
  ["@tag.delimiter"] = { fg = c.base0F, bg = 'NONE' },
  ["@tag.attribute"] = { link = '@Property' },
  ["@punctuation.bracket"] = { fg = c.base0F, bg = 'NONE' },
  ["@punctuation.special"] = { fg = c.base08, bg = 'NONE' },
  ["@string.regex"] = { fg = c.base0C, bg = 'NONE' },
  ["@string.escape"] = { fg = c.base0C, bg = 'NONE' },
  ["@emphasis"] = { fg = c.base09, bg = 'NONE' },
  ["@literal"] = { fg = c.base09, bg = 'NONE' },
  ["@text.uri"] = { fg = c.base09, bg = 'NONE' },
  ["@keyword.operator"] = { fg = c.base0E, bg = 'NONE' },
  ["@strong"] = { fg = 'NONE', bg = 'NONE', bold = true, },
  ["@scope"] = { fg = 'NONE', bg = 'NONE', bold = true, },
  TreesitterContext = { link = 'CursorLine' },

  -- markdown
  markdownBlockquote = { fg = c.green, bg = 'NONE' },
  markdownCode = { fg = c.orange, bg = 'NONE' },
  markdownCodeBlock = { fg = c.orange, bg = 'NONE' },
  markdownCodeDelimiter = { fg = c.orange, bg = 'NONE' },
  markdownH1 = { fg = c.blue, bg = 'NONE' },
  markdownH2 = { fg = c.blue, bg = 'NONE' },
  markdownH3 = { fg = c.blue, bg = 'NONE' },
  markdownH4 = { fg = c.blue, bg = 'NONE' },
  markdownH5 = { fg = c.blue, bg = 'NONE' },
  markdownH6 = { fg = c.blue, bg = 'NONE' },
  markdownHeadingDelimiter = { fg = c.blue, bg = 'NONE' },
  markdownHeadingRule = { fg = c.base05, bg = 'NONE', bold = true, },
  markdownId = { fg = c.purple, bg = 'NONE' },
  markdownIdDeclaration = { fg = c.blue, bg = 'NONE' },
  markdownIdDelimiter = { fg = c.light_grey, bg = 'NONE' },
  markdownLinkDelimiter = { fg = c.light_grey, bg = 'NONE' },
  markdownBold = { fg = c.blue, bg = 'NONE', bold = true, },
  markdownItalic = { fg = 'NONE', bg = 'NONE', italic = true, },
  markdownBoldItalic = { fg = c.yellow, bg = 'NONE', bold = true, italic = true, },
  markdownListMarker = { fg = c.blue, bg = 'NONE' },
  markdownOrderedListMarker = { fg = c.blue, bg = 'NONE' },
  markdownRule = { fg = c.base01, bg = 'NONE' },
  markdownUrl = { fg = c.cyan, bg = 'NONE', underline = true, },
  markdownLinkText = { fg = c.blue, bg = 'NONE' },
  markdownFootnote = { fg = c.orange, bg = 'NONE' },
  markdownFootnoteDefinition = { fg = c.orange, bg = 'NONE' },
  markdownEscape = { fg = c.yellow, bg = 'NONE' },

  -- Whichkey
  WhichKey = { fg = c.blue, bg = 'NONE' },
  WhichKeySeperator = { fg = c.light_grey, bg = 'NONE' },
  WhichKeyDesc = { fg = c.red, bg = 'NONE' },
  WhichKeyGroup = { fg = c.green, bg = 'NONE' },
  WhichKeyValue = { fg = c.green, bg = 'NONE' },
  WhichKeyFloat = { link = 'NormalFloat' },

  -- Git
  SignAdd = { fg = c.green, bg = 'NONE' },
  SignChange = { fg = c.blue, bg = 'NONE' },
  SignDelete = { fg = c.red, bg = 'NONE' },
  GitSignsAdd = { fg = c.green, bg = 'NONE' },
  GitSignsChange = { fg = c.blue, bg = 'NONE' },
  GitSignsDelete = { fg = c.red, bg = 'NONE' },

  -- LSP
  DiagnosticError = { fg = c.base08, bg = 'NONE' },
  DiagnosticWarning = { fg = c.base09, bg = 'NONE' },
  DiagnosticHint = { fg = c.purple, bg = 'NONE' },
  DiagnosticWarn = { fg = c.yellow, bg = 'NONE' },
  DiagnosticInfo = { fg = c.green, bg = 'NONE' },
  LspDiagnosticsDefaultError = { fg = c.base08, bg = 'NONE' },
  LspDiagnosticsDefaultWarning = { fg = c.base09, bg = 'NONE' },
  LspDiagnosticsDefaultInformation = { fg = c.sun, bg = 'NONE' },
  LspDiagnosticsDefaultInfo = { fg = c.sun, bg = 'NONE' },
  LspDiagnosticsDefaultHint = { fg = c.purple, bg = 'NONE' },
  LspDiagnosticsVirtualTextError = { fg = c.base08, bg = 'NONE' },
  LspDiagnosticsVirtualTextWarning = { fg = c.base09, bg = 'NONE' },
  LspDiagnosticsVirtualTextInformation = { fg = c.sun, bg = 'NONE' },
  LspDiagnosticsVirtualTextInfo = { fg = c.sun, bg = 'NONE' },
  LspDiagnosticsVirtualTextHint = { fg = c.purple, bg = 'NONE' },
  LspDiagnosticsFloatingError = { fg = c.base08, bg = 'NONE' },
  LspDiagnosticsFloatingWarning = { fg = c.base09, bg = 'NONE' },
  LspDiagnosticsFloatingInformation = { fg = c.sun, bg = 'NONE' },
  LspDiagnosticsFloatingInfo = { fg = c.sun, bg = 'NONE' },
  LspDiagnosticsFloatingHint = { fg = c.purple, bg = 'NONE' },
  DiagnosticSignError = { fg = c.base08, bg = 'NONE' },
  DiagnosticSignWarning = { fg = c.base09, bg = 'NONE' },
  DiagnosticSignInformation = { fg = c.sun, bg = 'NONE' },
  DiagnosticSignInfo = { fg = c.sun, bg = 'NONE' },
  DiagnosticSignHint = { fg = c.purple, bg = 'NONE' },
  LspDiagnosticsSignError = { fg = c.base08, bg = 'NONE' },
  LspDiagnosticsSignWarning = { fg = c.base09, bg = 'NONE' },
  LspDiagnosticsSignInformation = { fg = c.sun, bg = 'NONE' },
  LspDiagnosticsSignInfo = { fg = c.sun, bg = 'NONE' },
  LspDiagnosticsSignHint = { fg = c.purple, bg = 'NONE' },
  LspDiagnosticsError = { fg = c.base08, bg = 'NONE' },
  LspDiagnosticsWarning = { fg = c.base09, bg = 'NONE' },
  LspDiagnosticsInformation = { fg = c.sun, bg = 'NONE' },
  LspDiagnosticsInfo = { fg = c.sun, bg = 'NONE' },
  LspDiagnosticsHint = { fg = c.purple, bg = 'NONE' },
  LspDiagnosticsUnderlineError = { fg = 'NONE', bg = 'NONE', underline = true, },
  LspDiagnosticsUnderlineWarning = { fg = 'NONE', bg = 'NONE', underline = true, },
  LspDiagnosticsUnderlineInformation = { fg = 'NONE', bg = 'NONE', underline = true, },
  LspDiagnosticsUnderlineInfo = { fg = 'NONE', bg = 'NONE', underline = true, },
  LspDiagnosticsUnderlineHint = { fg = 'NONE', bg = 'NONE', underline = true, },
  LspReferenceRead = { fg = 'NONE', bg = '#2e303b' },
  LspReferenceText = { fg = 'NONE', bg = '#2e303b' },
  LspReferenceWrite = { fg = 'NONE', bg = '#2e303b' },
  LspCodeLens = { fg = c.base04, bg = 'NONE', italic = true, },
  LspCodeLensSeparator = { fg = c.base04, bg = 'NONE', italic = true, },

  -- Telescope
  TelescopeNormal = { fg = 'NONE', bg = c.darker_black },
  TelescopePreviewTitle = { fg = c.black, bg = c.green, bold = true, },
  TelescopePromptTitle = { fg = c.black, bg = c.red, bold = true, },
  TelescopeResultsTitle = { fg = c.darker_black, bg = c.darker_black, bold = true, },
  TelescopeSelection = { fg = c.white, bg = c.black2 },
  TelescopeBorder = { fg = c.darker_black, bg = c.darker_black },
  TelescopePromptBorder = { fg = c.black2, bg = c.black2 },
  TelescopePromptNormal = { fg = c.white, bg = c.black2 },
  TelescopePromptPrefix = { fg = c.red, bg = c.black2 },
  TelescopeResultsDiffAdd = { fg = c.green, bg = 'NONE' },
  TelescopeResultsDiffChange = { fg = c.blue, bg = 'NONE' },
  TelescopeResultsDiffDelete = { fg = c.red, bg = 'NONE' },

  -- StatusLine
  StatusLine = { fg = 'NONE', bg = c.statusline_bg },
  StatusLineNC = { fg = 'NONE', bg = c.grey },
  StatusLineTerm = { fg = 'NONE', bg = c.statusline_bg },
  StatusLineTermNC = { fg = c.grey_fg2, bg = c.statusline_bg },

  -- Cmp
  CmpItemAbbrDeprecated = { fg = c.grey, bg = 'NONE', strikethrough = true, },
  CmpItemAbbrMatch = { fg = c.blue, bg = 'NONE' },
  CmpItemAbbrMatchFuzzy = { fg = c.blue, bg = 'NONE' },
  CmpItemKindFunction = { fg = c.blue, bg = 'NONE' },
  CmpItemKindMethod = { fg = c.blue, bg = 'NONE' },
  CmpItemKindConstructor = { fg = c.cyan, bg = 'NONE' },
  CmpItemKindClass = { fg = c.cyan, bg = 'NONE' },
  CmpItemKindEnum = { fg = c.cyan, bg = 'NONE' },
  CmpItemKindEvent = { fg = c.yellow, bg = 'NONE' },
  CmpItemKindInterface = { fg = c.cyan, bg = 'NONE' },
  CmpItemKindStruct = { fg = c.cyan, bg = 'NONE' },
  CmpItemKindVariable = { fg = c.red, bg = 'NONE' },
  CmpItemKindField = { fg = c.red, bg = 'NONE' },
  CmpItemKindProperty = { fg = c.red, bg = 'NONE' },
  CmpItemKindEnumMember = { fg = c.orange, bg = 'NONE' },
  CmpItemKindConstant = { fg = c.orange, bg = 'NONE' },
  CmpItemKindKeyword = { fg = c.purple, bg = 'NONE' },
  CmpItemKindModule = { fg = c.cyan, bg = 'NONE' },
  CmpItemKindValue = { fg = c.base05, bg = 'NONE' },
  CmpItemKindUnit = { fg = c.base05, bg = 'NONE' },
  CmpItemKindText = { fg = c.base05, bg = 'NONE' },
  CmpItemKindSnippet = { fg = c.yellow, bg = 'NONE' },
  CmpItemKindFile = { fg = c.base05, bg = 'NONE' },
  CmpItemKindFolder = { fg = c.base0D, bg = 'NONE' },
  CmpItemKindColor = { fg = c.base05, bg = 'NONE' },
  CmpItemKindReference = { fg = c.base05, bg = 'NONE' },
  CmpItemKindOperator = { fg = c.base05, bg = 'NONE' },
  CmpItemKindTypeParameter = { fg = c.red, bg = 'NONE' },
}

require('highlights').apply_highlights(theme)
