# Colors (srcery)

# Default colors
[colors.primary]
background = '#1c1b19'
foreground = '#fce8c3'

# Normal colors
[colors.normal]
black   = '#918175'
red     = '#F75341'
green   = '#98BC37'
yellow  = '#FED06E'
blue    = '#68A8E4'
magenta = '#FF5C8F'
cyan    = '#2BE4D0'
white   = '#FCE8C3'

# Bright colors
[colors.bright]
black   = '#1C1B19'
red     = '#EF2F27'
green   = '#519F50'
yellow  = '#FBB829'
blue    = '#2C78BF'
magenta = '#E02C6D'
cyan    = '#0AAEB3'
white   = '#BAA67F'
