[general]
import = [
  # "xterm.toml",
  # "ayu.toml",
  # "base16_default_dark.toml",
  # "gruber_darker.toml",
  # "gruvbox_dark.toml.toml",
]

# [font]
# size = 10
# builtin_box_drawing = false
# [font.normal]
# family = "IosevkaTermSlab Nerd Font"

[font]
size = 13
offset = { x = 1, y = 1 }
builtin_box_drawing = true
[font.normal]
family = "Cozette"
# style = "HiDpi"

# [font]
# size = 9
# builtin_box_drawing = true
# [font.normal]
# family = "Terminess Nerd Font"

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

# [url]
# launcher = "xdg-open"
# modifiers = "Control"

[window]
dynamic_title = true
